### ISSUE TITLE
android playback error

### ISSUE THREAD

**Issue by stereoket** [kosso/ti-audioplayer#4]
the module wont run on android using 6.0.1 / 6.0.3.GA - on Android 6.0 I get module errors in the playback.

`04-10 19:12:30.047: I/TiAPI(16615):  player state change: 4`
`04-10 19:12:30.047: I/TiAPI(16615):  STATE_STARTING`
`04-10 19:12:30.061: I/TiAPI(16615):  player state change: 3`
`04-10 19:12:30.061: I/TiAPI(16615):  STATE_PLAYING`
`04-10 19:12:30.064: I/TiAPI(16615):  player ERROR:  {"type":"error","source":{"time":0,"volume":1,"url":"https://archive.org/download/testmp3testfile/mpthreetest.mp3","playing":false,"metadata":null,"paused":false,"streaming":false,"apiName":"com.kosso.audioplayerandroid","bubbleParent":true,"_events":{"durationavailable":{},"error":{},"complete":{},"playerstatuschange":{},"change":{},"seekcomplete":{},"progress":{}}},"message":"Unknown media error.","code":0,"bubbles":false,"cancelBubble":false}`

I haven't got any deeper in the debugging - but have tried on gennymotion / device and siwtched SDKs so far. 

I'm just using your iOS example code and switching between the modeuls with this:

`var audioplayer = (OS_IOS)?require('com.kosso.audioplayerios'):require('com.kosso.audioplayerandroid');`

using Alloy - to detect if iOS or not. The example code is your little example demo that was bundled in the ios module code. If I get any further info i'll post here.

**Comment by kosso** [comment]
Hi there. I just realised how old the example app is. 

I'm sorting out a new version and making sure the tests are better. 

But one crucial thing missing is for Android it needs a lifecycle container. (Which needs to be done differently with a single window app.js example.)

So, try creating the player after the window open event, with:

```
player = audioplayer.createPlayer({
  allowBackground: true,     // Android only. iOS version will ignore it. 
  lifecycleContainer: window // Android only. iOS version will ignore it. 
});
```

where `window` is naturally a handle on the current window.


You should eventually see the initialisation events happening, since we immediately load a url.

**Comment by stereoket** [comment]
aaaah. OK, I'm testing this out in a tab group example app - the docs state that it should point to a window or tab group reference. SO i'm setting it up like this:

```
var player = audioplayerios.createPlayer({
  allowBackground: true,     // Android only. iOS version will ignore it. 
  lifecycleContainer: Alloy.Globals.tabgroup // Android only. iOS version will ignore it. 
});
```

It tries to play, but I get a rash of android errors.

```
[ERROR] Surface: getSlotFromBufferLocked: unknown buffer: 0xe8dd7540
[ERROR] MediaPlayer: start called in state 4
[ERROR] MediaPlayer: error (-38, 0)
[INFO]  player state change: 4
[INFO]  STATE_STARTING
[ERROR] MediaPlayer: Error (-38,0)
[INFO]  player state change: 3
[INFO]  STATE_PLAYING
[ERROR] TiExceptionHandler: (main) [1135668,1206437] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,1206437] - In ti:/console.js:25,62
[ERROR] TiExceptionHandler: (main) [0,1206437] - Message: Uncaught TypeError: Converting circular structure to JSON
[ERROR] TiExceptionHandler: (main) [0,1206437] - Source: 				( arg.hasOwnProperty('toString') ? arg.toString() : JSON.stringify(arg) ) :
[ERROR] V8Exception: Exception occurred at ti:/console.js:25: Uncaught TypeError: Converting circular structure to JSON
[WARN]  EGL_emulation: eglSurfaceAttrib not implemented
[WARN]  OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xde058ec0, error=EGL_SUCCESS
[ERROR] Surface: getSlotFromBufferLocked: unknown buffer: 0xe8dd7460
```

**Comment by stereoket** [comment]
Even in the most basic of app setup:

```
Ti.Media.audioSessionCategory = Ti.Media.AUDIO_SESSION_CATEGORY_PLAYBACK;
//Be sure to also set background audio in tiapp.xml if you want it to play when sent to background.

var audioplayer = (OS_IOS)?require('com.kosso.audioplayerios'):require('com.kosso.audioplayerandroid');

var player = audioplayer.createPlayer({
  allowBackground: true,     // Android only. iOS version will ignore it. 
  lifecycleContainer: $.index // Android only. iOS version will ignore it. 
});

$.index.open();
// Short test
player.url = "https://archive.org/download/testmp3testfile/mpthreetest.mp3";
player.play();
```
I still get an error:

```
[ERROR] MediaPlayer: start called in state 4
[ERROR] MediaPlayer: error (-38, 0)
[ERROR] MediaPlayer: Error (-38,0)
```

But maybe this state 4 is the issue - I think this maps to _STATE_STARTING_ so perhaps I will need to wait for android state changes before I can trigger a play command.

**Comment by kosso** [comment]
Hi there. I just pushed up a full working example app in the `exmaple-app` branch.  (I'll stop mistyping *example*, one of these days ;) )

On first load, you need to wait for the right event before playing. The issue you're having is that it's not ready to play yet after setting the url. 

Try this branch: https://github.com/kosso/ti-audioplayer/tree/exmaple-app

**Comment by kosso** [comment]
Here's where all the gubbins is : 

https://github.com/kosso/ti-audioplayer/blob/exmaple-app/audioplayer-example/Resources/ui/common/window_home.js

**Comment by stereoket** [comment]
exmaple syrup is my favourite.

The exmaple app is all hunky dory - will weave  through  and tinker around  tomorrow.

Cheers,

**Comment by stereoket** [comment]
Ok weird stuff! - You example app works fine on its own, but when integrated within a tab group  it doesn't and triggers an error. 
Weird behaviour. Have you ever used this in a tab group setting?

Am going to run tests locally.

**Comment by stereoket** [comment]
OK, working by setting up the player on the index tabgroup creation controller. I am going to write a CommonJS  interface to the player and have each event listeners return an object so that its independent of the UI controls and the data it returns does not have to be used.

**Comment by stereoket** [comment]
Android is playing at half speed to iOS on the same file - when I first started testing, it was playing at twice the speed. I'm not smoking anything, honest.

**Comment by stereoket** [comment]
OK so I have functionality on android and have created a common JS module / interface - which needs a bit of work but a good way of hooking into it for both platforms. Need to work on state.
