### ISSUE TITLE
Android playback rate - half or double 1x speed

### ISSUE THREAD

**Issue by stereoket** [kosso/ti-audioplayer#5]
Strange speed rate differences - currently, android is playing back the remote mp3 at half the normal rate. As I implement my Common JS interface into my app I will try and unravel the differences.

**Comment by stereoket** [comment]
maybe something to do with the source bitrate.

**Comment by kosso** [comment]
That could very well be the case. I cobbled the Java together from a few other implementations of Android `MediaPlayer` out there to get something that did what I needed it to do.

Don't forget that in the situation I've needed to use these modules, the source audio is very much a known (and constant) entity.  ;)

**Comment by stereoket** [comment]
Genymotion Fail, its fine on device! the same issue with videos with the native player on genymotion.

**Comment by kosso** [comment]
I get weirdness from GenyMotion bit it works. I suppose it's down to the machine you're running it on?

**Comment by stereoket** [comment]
hmmm, not sure - a fairly recent MBP - and a newish image of geny ... if its working on device all is well. I'll worry about the emulation later. Will check the settings I reckon.

**Comment by stereoket** [comment]
3 days on from it all working - android audio now fails! Lots of android changes in that time, thankfully for git - i'm checking out historical  commits to find out what has gone wrong and where.... painful.

**Comment by kosso** [comment]
Argh.  Lifecycle?

**Comment by stereoket** [comment]
dunno, it works and then it doesn't work - with minor changes - lifecycle is on a tab group. so on the first window opened from the tab group - I instantiate the audio controller to a global - i'm busy wrapping up iOS bugs / tidy up to get it into the submission queue, then I'll take a closer look at the issues on android.

**Comment by stereoket** [comment]
It looks like it is lifecycle related - I can't get it stable

[ERROR] KrollProxy: (main) [102,17309] lifecycleContainer must be a WindowProxy or TabGroupProxy (TiWindowProxy)

I see this a lot, but as its baed on a tabgroup, and the audio page is a level below the first window of the first tab. Something weird is happening.


App Opens -> index creates tab group -> create audio object w/lifecycle -> open tab 1 window -> open window inside tab 1 -> use global audio player initialised at beginning of cycle -> play audio

That is the kind of thing. I'm trying weird and whacky ways round setting the audio engine. Sometimes it works, most of the time it doesn't

**Comment by kosso** [comment]
Hmm... I don't use TabGroups.

How about trying to create a (hidden) window somewhere in the root level and using that as the lifecycle container throughout the app? 

(I've also been known to be naughty and store the player reference at `Ti.App.audio_player`  .. ;) )

**Comment by stereoket** [comment]
haha - yes, I am going to have to get a little creative - couple of contracts ago they wanted a nav controller and then load a tab group - messed my delicate brain up. 

My next step was to see if the audio works at the root level in android, but I may have to get window crafty at app launch - no reason why i couldn't  create a window and a tab group as sep alloy elements in the same controller - I guess... 

> The top-level App module is mainly used for accessing information about the application at runtime, and for sending or listening for system events.

**Naughty** haha - gotta break them rules.

**Comment by stereoket** [comment]
Found the root cause - tabs in the Alloy.XML Tabgroup being set is fine, its the child tabs that cause the issue  - this disables the engine / lifecycle event somehow - I can replicate the behaviour. I'm now gonna try and figure out a programmatic way of doing this. Knowing what the issue is helps... a lot.
